import { z } from 'zod';

/**
 * Helper to coerce strings to booleans or numbers, useful for Env vars and YAML.
 */
const coerceBool = z.preprocess((val) => {
    if (typeof val === 'string') {
        if (val.toLowerCase() === 'true') return true;
        if (val.toLowerCase() === 'false') return false;
    }
    return val;
}, z.boolean());

const coerceNumber = z.preprocess((val) => {
    if (typeof val === 'string' && val.trim() !== '') {
        const parsed = Number(val);
        return isNaN(parsed) ? val : parsed;
    }
    return val;
}, z.number());

export const AgentConfigSchema = z.object({
    agentName: z.string().default('OrcBot'),
    llmProvider: z.enum(['openai', 'google', 'bedrock', 'openrouter', 'nvidia', 'anthropic']).optional(),
    providerModelNames: z.record(z.string(), z.string()).optional(),
    fallbackModelNames: z.record(z.string(), z.string()).optional(),
    telegramToken: z.string().optional(),
    openaiApiKey: z.string().optional(),
    openrouterApiKey: z.string().optional(),
    openrouterBaseUrl: z.string().default('https://openrouter.ai/api/v1'),
    openrouterReferer: z.string().optional(),
    openrouterAppName: z.string().optional(),
    googleApiKey: z.string().optional(),
    nvidiaApiKey: z.string().optional(),
    anthropicApiKey: z.string().optional(),
    braveSearchApiKey: z.string().optional(),
    searxngUrl: z.string().optional(),
    searchProviderOrder: z.array(z.string()).default(['serper', 'brave', 'searxng', 'google', 'bing', 'duckduckgo']),
    serperApiKey: z.string().optional(),
    captchaApiKey: z.string().optional(),
    modelName: z.string().default('gpt-4o'),
    bedrockRegion: z.string().optional(),
    bedrockAccessKeyId: z.string().optional(),
    bedrockSecretAccessKey: z.string().optional(),
    bedrockSessionToken: z.string().optional(),
    autonomyEnabled: coerceBool.default(true),
    autonomyInterval: coerceNumber.default(15),
    autonomyPostUserCooldownSeconds: coerceNumber.default(90),
    autonomyBacklogLimit: coerceNumber.default(3),
    autonomyAllowedChannels: z.array(z.string()).default([]),
    workerPoolAllowAutonomyDuringUserWork: coerceBool.default(false),
    maxActionRunMinutes: coerceNumber.default(10),
    maxStaleActionMinutes: coerceNumber.default(30),
    memoryPath: z.string().optional(),
    skillsPath: z.string().optional(),
    userProfilePath: z.string().optional(),
    agentIdentityPath: z.string().optional(),
    actionQueuePath: z.string().optional(),
    journalPath: z.string().optional(),
    learningPath: z.string().optional(),
    pluginsPath: z.string().optional(),
    toolsPath: z.string().optional(),
    whatsappEnabled: coerceBool.default(false),
    whatsappSessionPath: z.string().optional(),
    whatsappAutoReplyEnabled: coerceBool.default(false),
    whatsappStatusReplyEnabled: coerceBool.default(false),
    whatsappAutoReactEnabled: coerceBool.default(false),
    whatsappContextProfilingEnabled: coerceBool.default(false),
    whatsappOwnerJID: z.string().optional(),
    telegramAutoReplyEnabled: coerceBool.default(false),
    maxMessagesPerAction: coerceNumber.default(10),
    maxStepsPerAction: coerceNumber.default(30),
    messageDedupWindow: coerceNumber.default(10),
    commandTimeoutMs: coerceNumber.default(120000),
    commandRetries: coerceNumber.default(1),
    commandWorkingDir: z.string().optional(),
    buildWorkspacePath: z.string().optional(),
    commandAllowList: z.array(z.string()).default([
        'npm', 'node', 'npx', 'git', 'python', 'pip', 'pip3', 'curl', 'wget', 'powershell',
        'pwsh', 'bash', 'apt', 'apt-get', 'yum', 'dnf', 'pacman', 'brew', 'sudo', 'systemctl',
        'service', 'cat', 'ls', 'dir', 'echo', 'mkdir', 'touch', 'cp', 'mv', 'head', 'tail',
        'grep', 'find', 'which', 'whoami', 'uname', 'hostname'
    ]),
    commandDenyList: z.array(z.string()).default([
        'rm', 'rmdir', 'del', 'erase', 'format', 'mkfs', 'dd', 'shutdown', 'reboot', 'poweroff',
        'reg', 'diskpart', 'netsh'
    ]),
    safeMode: coerceBool.default(false),
    sudoMode: coerceBool.default(false),
    overrideMode: coerceBool.default(false),
    pluginAllowList: z.array(z.string()).default([]),
    pluginDenyList: z.array(z.string()).default([]),
    pluginHealthCheckIntervalMinutes: coerceNumber.default(15),
    browserProfileDir: z.string().optional(),
    browserProfileName: z.string().default('default'),
    browserEngine: z.enum(['playwright', 'lightpanda']).default('playwright'),
    lightpandaEndpoint: z.string().default('ws://127.0.0.1:9222'),
    lightpandaPath: z.string().optional(),
    browserDebugAlwaysSave: coerceBool.default(false),
    browserTraceEnabled: coerceBool.default(false),
    browserTraceDir: z.string().optional(),
    browserTraceScreenshots: coerceBool.default(true),
    browserTraceSnapshots: coerceBool.default(true),
    googleComputerUseEnabled: coerceBool.default(false),
    googleComputerUseModel: z.string().default('gemini-2.5-computer-use-preview-10-2025'),
    tokenUsagePath: z.string().optional(),
    tokenLogPath: z.string().optional(),
    discordToken: z.string().optional(),
    discordAutoReplyEnabled: coerceBool.default(false),
    slackBotToken: z.string().optional(),
    slackAppToken: z.string().optional(),
    slackSigningSecret: z.string().optional(),
    slackAutoReplyEnabled: coerceBool.default(false),
    emailEnabled: coerceBool.default(false),
    emailAutoReplyEnabled: coerceBool.default(false),
    emailAddress: z.string().optional(),
    emailFromName: z.string().optional(),
    emailDefaultSubject: z.string().default('OrcBot response'),
    emailSocketTimeoutMs: coerceNumber.default(15000),
    smtpHost: z.string().optional(),
    smtpPort: coerceNumber.default(587),
    smtpSecure: coerceBool.default(false),
    smtpStartTls: coerceBool.default(true),
    smtpUsername: z.string().optional(),
    smtpPassword: z.string().optional(),
    imapHost: z.string().optional(),
    imapPort: coerceNumber.default(993),
    imapSecure: coerceBool.default(true),
    imapUsername: z.string().optional(),
    imapPassword: z.string().optional(),
    worldEventsSources: z.array(z.string()).default(['gdelt', 'usgs']),
    worldEventsRefreshSeconds: coerceNumber.default(60),
    worldEventsLookbackMinutes: coerceNumber.default(60),
    worldEventsMaxRecords: coerceNumber.default(250),
    worldEventsBatchMinutes: coerceNumber.default(10),
    worldEventsStoreEnabled: coerceBool.default(true),
    worldEventsHeartbeatEnabled: coerceBool.default(true),
    worldEventsGdeltQuery: z.string().default('global'),
    worldEventsGlobeRenderer: z.enum(['ascii', 'external', 'map', 'mapscii']).default('mapscii'),
    worldEventsGlobeCommand: z.string().default('mapscii'),
    worldEventsGlobeArgs: z.array(z.string()).default([]),
    sessionScope: z.enum(['main', 'per-peer', 'per-channel-peer']).default('per-channel-peer'),
    identityLinks: z.record(z.string(), z.string()).default({}),
    guidanceMode: z.enum(['strict', 'balanced', 'fluid']).default('balanced'),
    guidanceAckPatterns: z.array(z.string()).default([
        '^(understood|got it|on it|acknowledged|okay|ok|alright|sure|perfect)\b',
        '^thanks?[,.!\s]',
        "\bi\s*(am|'m)\s*(ready|working on|going to|about to)\b",
        '\bi\s*will\s*now\b',
        '\bworking on it\b',
        '\blet me\b'
    ]),
    guidanceLowValuePatterns: z.array(z.string()).default([
        '^(got it|on it|working on it|one moment|hang tight|be right back|still working)[.!]?$',
        "^i('m| am) (checking|working on|looking into)\b",
        '^quick update[:\-]?\s*$',
        '^sorry[,\s]',
        '^(understood|acknowledged)[,.!\s]',
        "\bi\s*(am|'m)\s*ready\s*to\b",
        '\bi\s*will\s*now\b'
    ]),
    guidanceClarificationKeywords: z.array(z.string()).default([
        'clarif', 'question', 'which', 'what', 'prefer', 'preference', 'confirm', 'api', 'details'
    ]),
    guidanceQuestionStopWords: z.array(z.string()).default([
        'the', 'a', 'an', 'and', 'or', 'to', 'for', 'of', 'in', 'on', 'at', 'is', 'are', 'was', 'were',
        'be', 'been', 'being', 'do', 'does', 'did', 'can', 'could', 'would', 'should', 'will', 'please',
        'you', 'your', 'me', 'my', 'we', 'our', 'it', 'this', 'that', 'with', 'about', 'if', 'as', 'by'
    ]),
    guidanceRepeatQuestionThreshold: coerceNumber.default(0.65),
    guidanceShortReplyMaxWords: coerceNumber.default(7),
    guidanceShortReplyMaxChars: coerceNumber.default(48),
    robustReasoningMode: coerceBool.default(false),
    reasoningExposeChecklist: coerceBool.default(false),
    reasoningChecklistMaxItems: coerceNumber.default(5),
    orcbotControlEnabled: coerceBool.default(true),
    orcbotControlCliAllowList: z.array(z.string()).default(['config get', 'config set', 'models', 'gateway', 'security', 'agentic-user']),
    orcbotControlCliDenyList: z.array(z.string()).default(['reset', 'ui', 'setup', 'builder', 'daemon stop']),
    orcbotControlTimeoutMs: coerceNumber.default(45000),
    autoExecuteCommands: coerceBool.default(false),
    skillRoutingRules: z.array(z.object({
        match: z.string(),
        prefer: z.array(z.string()).optional(),
        avoid: z.array(z.string()).optional(),
        requirePreferred: z.boolean().optional()
    })).default([]),
    autopilotNoQuestions: coerceBool.default(false),
    autopilotNoQuestionsAllow: z.array(z.string()).default([]),
    autopilotNoQuestionsDeny: z.array(z.string()).default([]),
    progressFeedbackEnabled: coerceBool.default(true),
    progressFeedbackStepInterval: coerceNumber.default(4),
    progressFeedbackForceInitial: coerceBool.default(true),
    progressFeedbackTypingOnly: coerceBool.default(true),
    enforceExplicitFileRequestForSendFile: coerceBool.default(false),
    onboardingQuestionnaireEnabled: coerceBool.default(true),
    reconnectBriefingEnabled: coerceBool.default(true),
    reconnectBriefingThresholdDays: coerceNumber.default(3),
    reconnectBriefingMaxCompletions: coerceNumber.default(5),
    reconnectBriefingMaxPending: coerceNumber.default(3),
    recoveryDedupWindowHours: coerceNumber.default(6),
    usagePingEnabled: coerceBool.default(true),
    usagePingUrl: z.string().default(''),
    usagePingTimeoutMs: coerceNumber.default(4000),
    usagePingToken: z.string().default(''),
    memoryContentMaxLength: coerceNumber.default(500),
    memoryFlushSoftThreshold: coerceNumber.default(25),
    memoryFlushCooldownMinutes: coerceNumber.default(30),
    memoryExtendedContextLimit: coerceNumber.default(2000),
    threadContextRecentN: coerceNumber.default(8),
    threadContextRelevantN: coerceNumber.default(8),
    threadContextMaxLineLen: coerceNumber.default(420),
    threadContextOtherMemoriesN: coerceNumber.default(5),
    journalContextLimit: coerceNumber.default(1500),
    learningContextLimit: coerceNumber.default(1500),
    userContextLimit: coerceNumber.default(2000),
    stepCompactionThreshold: coerceNumber.default(10),
    stepCompactionPreserveFirst: coerceNumber.default(2),
    stepCompactionPreserveLast: coerceNumber.default(5),
    stepCompactionExpandOnDemand: coerceBool.default(true),
    stepCompactionExpansionMaxMiddleSteps: coerceNumber.default(12),
    stepCompactionExpansionMaxChars: coerceNumber.default(2400),
    memoryInteractionBatchSize: coerceNumber.default(12),
    memoryInteractionStaleMinutes: coerceNumber.default(10),
    memoryDedupWindowMinutes: coerceNumber.default(5),
    userExchangeContextLimit: coerceNumber.default(8),
    timeSignalHighRiskNoMessageSeconds: coerceNumber.default(25),
    timeSignalMediumRiskSilentSteps: coerceNumber.default(4),
    timeSignalMediumRiskSinceDeliverySeconds: coerceNumber.default(45),
    sessionAnchorEnabled: coerceBool.default(true),
    sessionAnchorMaxHints: coerceNumber.default(4),
    memoryContextLimit: coerceNumber.default(20),
    memoryEpisodicLimit: coerceNumber.default(5),
    memoryConsolidationThreshold: coerceNumber.default(30),
    memoryConsolidationBatch: coerceNumber.default(20),
    skipSimulationForSimpleTasks: coerceBool.default(true),
    compactSkillsPrompt: coerceBool.default(false),
    fastModelName: z.string().optional(),
    gatewayPort: coerceNumber.default(3100),
    gatewayHost: z.string().default('0.0.0.0'),
    gatewayApiKey: z.string().optional(),
    gatewayCorsOrigins: z.array(z.string()).default(['*']),
    imageGenProvider: z.enum(['openai', 'google']).optional(),
    imageGenModel: z.string().optional(),
    imageGenSize: z.string().default('1024x1024'),
    imageGenQuality: z.string().default('medium'),
    agenticUserEnabled: coerceBool.default(false),
    agenticUserResponseDelay: coerceNumber.default(120),
    agenticUserConfidenceThreshold: coerceNumber.default(70),
    agenticUserProactiveGuidance: coerceBool.default(true),
    agenticUserProactiveStepThreshold: coerceNumber.default(8),
    agenticUserCheckInterval: coerceNumber.default(30),
    agenticUserMaxInterventions: coerceNumber.default(3),
    agenticUserNotifyUser: coerceBool.default(true),
    serverMode: coerceBool.default(false),
    actionQueueCompletedTTL: coerceNumber.default(24 * 60 * 60 * 1000),
    actionQueueFailedTTL: coerceNumber.default(72 * 60 * 60 * 1000),
    actionQueueFlushIntervalMs: coerceNumber.default(5000),
    actionQueueMaintenanceIntervalMs: coerceNumber.default(60000),
    vectorMemoryMaxEntries: coerceNumber.default(5000),
    processedMessagesCacheSize: coerceNumber.default(1000),
    usePiAI: coerceBool.default(true),
    groqApiKey: z.string().optional(),
    mistralApiKey: z.string().optional(),
    cerebrasApiKey: z.string().optional(),
    xaiApiKey: z.string().optional(),
    tforceEnabled: coerceBool.default(true),
    tforceMaxIncidentsPerAction: coerceNumber.default(30),
    adminUsers: z.object({
        telegram: z.array(z.string()).optional(),
        discord: z.array(z.string()).optional(),
        whatsapp: z.array(z.string()).optional(),
        slack: z.array(z.string()).optional(),
        email: z.array(z.string()).optional()
    }).default({}),
    telegramCommands: z.array(z.object({
        command: z.string(),
        description: z.string()
    })).default([
        { command: 'status', description: 'Check agent health and queue status' },
        { command: 'reset', description: 'Reset conversation context (clears short-term memory)' },
        { command: 'help', description: 'Show all available commands' },
        { command: 'search', description: 'Trigger a web search task' }
    ]),
    // Allow dynamic keys (e.g. MOLTBOOK_API_KEY)
}).catchall(z.any());

export type AgentConfig = z.infer<typeof AgentConfigSchema>;
